import type {AppProps} from "next/app";
import Head from "next/head";
import {GlobalStyle} from "@/styles/globals";

export default function App({Component, pageProps}: AppProps) {
    return (
        <>
            <GlobalStyle/>
            <Head>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <Component {...pageProps} />;
        </>
    );
}
